### ISSUE TITLE
スタッフの役割と人数を決める

### ISSUE THREAD

**Issue by 1syo** [yokohamarb/minatork02#1]
- 実行委員３名の役割
- 当日スタッフ若干名の役割

**Comment by 1syo** [comment]
- 当日必要そうな役割
  - 設営(全員参加！？)
  - 司会 x 1
  - 音響&証明 x 1
  - 受付 x 2
  - るびま x2
  - ドアマンx2
  - 懇親会引率

くらいか？

**Comment by 1syo** [comment]
- 当日までに必要そうな役割
  - 実行委員長
  - 会計
  - るびま棟梁
  - ウェブページ
  - 募集ページ
  - 懇親会関係

**Comment by 1syo** [comment]
Add 音響&証明 x 1

**Comment by miyohide** [comment]
@1syo さん、 @chezou さん。
懇親会についてですが、1点相談です。
個人的な思いとして、懇親会を我々がセッティングする必要はないように考えます。理由は次の点です。
- 運営コストが高い。会計、人数把握、店確保等々。
  - そこに体力を割くのは惜しい。
- 飲み屋はそこら辺にたくさんあるので、適当な店をラインナップするぐらいでいいのでは？

**Comment by miyohide** [comment]
ひょっとして、るびま棟梁＝みよひで？

**Comment by chezou** [comment]
懇親会は渋谷のように各自で、という形でも良いかもしれませんね。
公募はしない形でも発表者を中心とした打ち上げは開催しても良いと思います
