### ISSUE TITLE
夜も眠れない問題について話す

### ISSUE THREAD

**Issue by 1syo** [yokohamarb/minatork02#11]
- 当日お子様の運動会で登壇予定の方が参加できなかったらどうしよう

**Comment by 1syo** [comment]
最悪でも動画で発表してもらえるとかできそう..

**Comment by miyohide** [comment]
運動会なんかで参加できなくなるっていうのは、事前にある程度わかることなのであまり心配していません。わかった段階で声を上げてくれたらなんとでも対処可能なので。

当日、体調不良とかで参加できなくなった場合を考える必要があります。その際は、例えば、
- 午前中で参加可能かどうか判断する。
  - 午前中で参加不可と判断した場合は、昼休憩を長めに取るとか、セッション間の休憩を長くとるとか。
  - 最後の最後は、終了時刻を早めるとか。
