### ISSUE TITLE
スピーカーに依頼をする

### ISSUE THREAD

**Issue by miyohide** [yokohamarb/minatork02#13]
スピーカーになってほしい人にお声がけして、スケジュールの確保と発表内容を考えてもらうようにお願いをする。

今のところ、スピーカーとして考えている人を上げていただけると嬉しいです。今のところ認識しているのは、私だけ...
- @miyohide （ @1syo さんから依頼されている）

**Comment by chezou** [comment]
- @nabetani さん
- @igrep さん

あたりも、いっしょーさんと良く話で出ていたと思います

**Comment by miyohide** [comment]
Yokohama.rb参加経験者に対するスピーカー公募の連絡文言を考えてみました。

募集締め切り、結果連絡の日付は仮ぎめです。○○○はスタッフのメールアドレス全員を入れようかと思っています。

ご意見いただけますでしょうか。

> 来る2015年10月11日（日）に、みなとRuby会議02を開催することになりました。
> 
> そこで、Yokohama.rbに参加経験がある皆様を対象に、以下の要項で
> みなとRuby会議02のスピーカーを公募いたします。なお、応募数が発表枠を
> 超えた場合は、スタッフによる審査を行い、スピーカーを決定いたします。
> 
> みなさまの奮ってのご応募をお待ちしております。
> 
> 【応募要項】
> 1）募集対象者
> 　　Yokohama.rbに過去に一度以上参加したことがある人
> 
> 2）募集締め切り
> 　　2015年6月30日 23:59
> 
> 3）応募方法
> 　　以下の情報を明記の上、○○○までメールを送信願います。
> 　　　・お名前（ふりがな）
> 　　　・メールアドレス
> 　　　・発表予定タイトル（仮）
> 　　　・発表概要
> 
> 4）採択結果のご連絡
> 　　2015年7月10日ごろ。採択結果にかかわらず、全員にご連絡いたします。

**Comment by chezou** [comment]
よさそうです

**Comment by igrep** [comment]
LGTMです！ :+1:

**Comment by miyohide** [comment]
発表テーマと、問合せ先を明記する必要がありますね。後で追記しておきます。

発表テーマってなんだっけ？

**Comment by 1syo** [comment]
みよひでさん thx!

外向けのテーマは生活発表会です。
Yokohamarbメンバーが普段興味をもって取り組んでいる技術的な活動について発表してもらいたいです。

**Comment by miyohide** [comment]
書き直しました。また、日付も調整しました。

OKであれば、これで出そうかと思います。

> 来る2015年10月11日（日）に、みなとRuby会議02を開催することになりました。
> 
> そこで、Yokohama.rbに参加経験がある皆様を対象に、以下の要項で
> みなとRuby会議02のスピーカーを公募いたします。なお、応募数が発表枠を
> 超えた場合は、スタッフによる審査を行い、スピーカーを決定いたします。
> 
> 発表テーマは「生活発表会」です。Yokohama.rbに参加されているかたが、
> 普段興味を持って取り組んでいる技術的な活動について発表をお願いします。
> 
> みなさまの奮ってのご応募をお待ちしております。
> 
> 【応募要項】
> 1）募集対象者
> 　　Yokohama.rbに過去に一度以上参加したことがある人
> 
> 2）募集締め切り
> 　　2015年6月27日（土） 23:59
> 
> 3）応募方法
> 　　以下の情報を明記の上、みよひで（○○○）にメールを送信願います。
> 　　　・お名前（ふりがな）
> 　　　・メールアドレス
> 　　　・発表予定タイトル（仮）
> 　　　・発表概要
> 
> 4）採択結果のご連絡
> 　　2015年7月12日（日）ごろ。採択結果にかかわらず、全員にご連絡いたします。
> 
> 5) 問い合わせ先
>        みよひで（○○○）

**Comment by chezou** [comment]
LGTM :shipit:

**Comment by 1syo** [comment]
LGTM +1

**Comment by miyohide** [comment]
doorkeeperの機能を使ってメッセージを送りました（受信確認済み）。これで、このIssueはCloseします。
