### ISSUE TITLE
Presenter decision meeting

### ISSUE THREAD

**Issue by miyohide** [yokohamarb/minatork02#17]
7月12日（日）前までに発表者を決めるためのミーティングをしたいです。

調整さんを立てたので入力お願いします。
https://chouseisan.com/schedule/List?h=d2755a322512401880d983dd60a6feb9

日付・時刻は仮ぎめですので、都合が悪い時はご自身の都合が良い日時を教えて下さい。

オフラインを考えていますが、オンラインのほうが良いという場合はその旨をご連絡ください。

**Comment by miyohide** [comment]
@igrep さん、すみません、本件は発表者さんを決めるためのミーティングとなりますので、スタッフオンリーとさせてください。

混同させてしまい、済みません。

**Comment by igrep** [comment]
おお、すみません。スタッフは発表者持ち回り、と伺っていたので含まれるかなと思ってました。
まぁ、でもよく考えたら発表者が選ぶミーティングに出るのもおかしいですしね。
削除します。

**Comment by miyohide** [comment]
@igrep さん、対応有難うございます。
スタッフは発表者とは別です。発表に集中していただければと。
