### ISSUE TITLE
第一回実行委員会議を行う

### ISSUE THREAD

**Issue by 1syo** [yokohamarb/minatork02#2]

**Comment by miyohide** [comment]
どこかで集まることできますか？
直近ですと、4/17（金）の「ペアプロお疲れ様飲み会」が全員集まるのですが、さすがにその場で話すのはちょっと気が引けます。

平日夜間にちょっとご飯でも食べながらって感じでしょうか。
それとも週末（土日）の昼間にでも集まるって感じでしょうか。

@1syo さんと @chezou さんはどのような思いでしょうか。

**Comment by 1syo** [comment]
ちょっと今立て込んですので週明けとかに調整さん立てます。
５月中旬までにやりたい印象です。

**Comment by miyohide** [comment]
調整さんを立ててみました。 @1syo さん、 @chezou さん、入力お願いします。
https://chouseisan.com/schedule/List?h=9f19f82d64784bf2938a77b4fcfd75ec

**Comment by 1syo** [comment]
この時に決めたいのは以下の３つかな
https://github.com/yokohamarb/minatork02/issues/1
https://github.com/yokohamarb/minatork02/issues/7
https://github.com/yokohamarb/minatork02/issues/3

ほかは時間があれば話したいけど、事後オンラインでもできそうな印象ある

**Comment by chezou** [comment]
調整さん書きました
5/1,8,9,12といったところでしょうか

**Comment by 1syo** [comment]
5/9 がOKなら5/9にしたいなぁ

**Comment by chezou** [comment]
:ok_woman:

**Comment by 1syo** [comment]
5/9（土）でGoogleカレンダーに招待送りましたー
よろしくです

**Comment by miyohide** [comment]
2015/05/09 (土) 14:00 ～ 16:30 、タネマキさんで開催します。よろしくお願いします。

**Comment by miyohide** [comment]
本件、とりあえず延期します。

**Comment by 1syo** [comment]
今月中にオンラインで開催できないだろうか... とはいえ予定見えなんだよなぁ...
僕の都合で申し訳ない..

**Comment by miyohide** [comment]
短い時間でも良いので、オンラインでやりたいですね。skypeなんかでやりたいです。

**Comment by chezou** [comment]
skypeで良いですよ。都合が良い日を後ほどお知らせ下さい

**Comment by 1syo** [comment]
明日（5/18）ステータス変わるので調整は明日（5/18）以降にさせてください

**Comment by chezou** [comment]
:ok_woman:
