### ISSUE TITLE
当日のスケジュールを決める

### ISSUE THREAD

**Issue by 1syo** [yokohamarb/minatork02#4]

**Comment by 1syo** [comment]
## 案1

| 開始 | 終了 | セッション |
| --- | --- | --- |
| 10:30 | 10:40 | オープニング |
| 10:40 | 11:00 | 1 |
| 11:00 | 11:20 | 2 |
| 11:20 | 11:40 | 3 |
| 11:40 | 13:00 | 昼 |
| 13:00 | 13:20 | 5 |
| 13:20 | 13:40 | 6 |
| 13:40 | 14:00 | 7 |
| 14:00 | 14:30 | 休憩 |
| 14:30 | 14:50 | 8 |
| 14:50 | 15:10 | 9 |
| 15:10 | 15:30 | 10 |
| 15:30 | 16:00 | 休憩 |
| 16:00 | 16:20 | 11 |
| 16:20 | 16:30 | クロージング |

休憩の後に11枠があっていまいちなんだよな

**Comment by miyohide** [comment]
@1syo 開始時間をちょっと遅らせて、10枠にしませんか？

**Comment by 1syo** [comment]
ちょっと調整してみる

**Comment by 1syo** [comment]
| 開始 | 終了 | セッション |
| --- | --- | --- |
| 11:00 | 11:10 | オープニング |
| 11:10 | 11:30 | 1 |
| 11:30 | 11:50 | 2 |
| 11:50 | 13:00 | 昼 |
| 13:00 | 13:20 | 3 |
| 13:20 | 13:40 | 4 |
| 13:40 | 14:00 | 5 |
| 14:00 | 14:20 | 休憩 |
| 14:20 | 14:40 | 6 |
| 14:40 | 15:00 | 7 |
| 15:00 | 15:20 | 8 |
| 15:20 | 15:40 | 休憩 |
| 15:40 | 16:00 | 9 |
| 16:00 | 16:20 | 10 |
| 16:20 | 16:30 | クロージング |

**Comment by 1syo** [comment]
直した

**Comment by chezou** [comment]
会場を借りている時間は9時-17時の枠ですか？

**Comment by miyohide** [comment]
@chezou はい。会場借りているのは9時〜17時の枠です。その後の枠も埋まっているため、17:00には完全撤収が必要です。

**Comment by miyohide** [comment]
@1syo @chezou 今日、 @1syo さんにはお話したのですが、お昼は90分はほしいという思いがあります。

**Comment by 1syo** [comment]
9時〜17時なんですが、設営、撤去など考慮してます。
昼休み90分で再検討します。

**Comment by chezou** [comment]
規模にもよるかもしれませんが、クロージングが 16:30 なのが少し気になりました。
(そこから、片付けと完全撤収できるかも含めて)

開始は問題無いと思います。

**Comment by miyohide** [comment]
片付けはホール内の掃除と、忘れ物チェック、各種道具の後片付けがタスクです。施設の方が言うには、だいたい10分ぐらいで終わるというお話でした（ホンマに？とは思いますが）。

聴衆をいかに捌くかがポイントとなりそうです。

**Comment by 1syo** [comment]
夜の部の開始時間が17:30なので17:00ギリギリでも大丈夫だとは思うけど、土曜日ホールの人に聞いてみた方がいいですね。
