### ISSUE TITLE
会場の下見をする

### ISSUE THREAD

**Issue by 1syo** [yokohamarb/minatork02#5]
- 4/12 10:00から下見です
## 目的
- [x] 会場設備の確認
  - [x] プロジェクターをどこに置くか
  - [x] スクリーンはどうやって上げ下げするか
  - [x] 登壇者はどこに立つか
  - [x] 音響機器の使い方
- [x] レンタルする機材は以下で十分か
  - [x] マイク(何本)
  - [x] プロジェクター
- [x] 受付の場所の見積もり
- [x] ドアマンの必要性の見積もり

**Comment by 1syo** [comment]
- [x] 会場設備の確認
  - [x] プロジェクターをどこに置くか
    - 前から３列目までは固定の椅子ではないのでその一部を撤去してプロジェクターを設置する
    - 設置用の台は会場にあるのを借りることができる
    - プロジェクターから登壇者の場所まで10mほどあるが、その長さを満たすVGAケーブルを借りられる
    - 電源は上手舞台下にあるのでそこから取得できる
    - 但しケーブルは養生テープで固定したほうがよさそう
  - [x] スクリーンはどうやって上げ下げするか
    - 上手側に集約されているが、設営のときに下ろしてしまってよいと思う。
  - [x] 登壇者はどこに立つか
    - 上手に台を設置する
    - スポットライトをあてる
    - 電源は上手舞台脇にあるのでそこから取得できる
  - [x] 音響機器の使い方
    - 上手舞台袖に音響、証明がまとまって設置されている。
    - マイクは6台、1〜6で操作可能
    - 証明は舞台全体、登壇者、過客席の3箇所をいじれば良さそう
- [x] レンタルする機材は以下で十分か
  - [x] マイク(何本)
    - 合計で6本あるそう。すべて無線。
  - [x] プロジェクター
    - 10mほどの電源ケーブル、VGAアダプター込でかりられる
- [x] 受付の場所の見積もり
  - 受つけ用のテーブルはたくさんある
  - ホワイエに設営すればよさそう
- [x] ドアマンの必要性の見積もり
  - ドアは舞台付近左右に２箇所、客席後部に２箇所の全部で4箇所ある
  - 防犯上の理由で鍵を掛けることはできない
  - 舞台付近の２箇所は閉じっぱなしでよさそう。
  - 客席後部の２箇所にドアマンがいたほうが良さそうな印象。

**Comment by 1syo** [comment]
- 控室
  - 舞台袖に控室あり。
  - 鍵は借りられるそう。
- ホワイエ
  - 2箇所一般的な電源があるのでそこを利用して電源コーナーにするのがよさそう
- トイレ
  - 上手側と入り口付近の２箇所ある
  - 上手のトイレの方が容量が大きい

**Comment by 1syo** [comment]
@chezou ざっと一読してもらえると。別途説明の機会は設けます。

**Comment by 1syo** [comment]
[感想]
舞台に立つとだいぶ広さを感じる本格的なホールだった
600名弱はホールとしては小さいけど十分な雰囲気があり理想的

当選してくれたみよひでさんに改めて感謝したい

**Comment by miyohide** [comment]
@1syo さん。
舞台付近のトイレに近い方は休憩時間に開けておいたほうがよいかなと感じました。

**Comment by miyohide** [comment]
ホールの最大収容人数について。約500名（494名）を見込んでいます。

最大席数は575席あるのですが、パイプ椅子の部分が78席あり、ここにはプロジェクターやらるびまレポート班やら、スタッフ待機用にしようかと考えています。
車いす席が3席分あり、それらを除いて494名がMaxという計算です。

**Comment by miyohide** [comment]
携帯の電波ですが、Softbankは4Gで5本中3本のアンテナがたちました（ドアを閉めた時にホールで確認したところ）。ちょっと通信は遅いかなって感じです。
