### ISSUE TITLE
会場への精算

### ISSUE THREAD

**Issue by 1syo** [yokohamarb/minatork02#6]
4/18(土) には払いに行く

**Comment by miyohide** [comment]
25,200円を4月12日（日）に支払いました。支払者は @miyohide です。

**Comment by miyohide** [comment]
本日、会場提供者から電話連絡があり、料金の計算が間違っていたので不足分を払ってほしいとのこと。
というわけで、本Issue、Reopenします。
支払いは、今週土曜日（4/18）に行う予定です。要領収書。

**Comment by miyohide** [comment]
4月18日（土）に追加料金3,000円を支払いました。支払者は @miyohide です。
