### ISSUE TITLE
会議までの詳細なスケジュールを決める

### ISSUE THREAD

**Issue by 1syo** [yokohamarb/minatork02#7]
## 最初につくった雑なスケジュール
- 7/11(土)  発表者募集 
- 8/8(土)  発表者確定
- 8月中  プログラム確定
- 9月初旬  参加者募集開始
- 10/11(日)  本番 
## 漏れてそうなの
- スライドを事前に提出してもらいチェックする
- 当日スタッフオリエンテーション
- ほかあるかな？

**Comment by miyohide** [comment]
7月末ぐらいに発表者募集締め切りが必要かと思われます。
