### ISSUE TITLE
webページ作る

### ISSUE THREAD

**Issue by 1syo** [yokohamarb/minatork02#8]
https://github.com/ruby-no-kai/regional-rubykaigi-orgz/issues/2

**Comment by chezou** [comment]
サイトに必要な情報をリストアップする

**Comment by miyohide** [comment]
5月16日（土）現在で公開できる情報は、以下だと思っています。
- 開催日（2015年10月11日（日））
- 時間（予定）（11:00〜16:30）
- 開催場所（西区公会堂）
- 募集人数（予定）（500人）
- 料金（予定）（900円程度）

以下は、まだ掲載できない情報と考えています。
- 開催趣旨
- タイムスケジュール・発表予定者
- 参加者登録ページ（doorkeeper？）

後は、ページの作り方ですが、みなと01のページをコピーして ruby-no-kai/regional-rubykaigi-orgz#2 の「rrko内にサイトを用意する場合」に沿ってPull Requestを出せば良さそう。

**Comment by miyohide** [comment]
簡単に作ってみました。
https://github.com/yokohamarb/regional.rubykaigi.org/blob/minato02/minato02/index.html
ご意見いただけますでしょうか。

**Comment by chezou** [comment]
とりあえず最初の情報としては、良さそうです。

**Comment by miyohide** [comment]
@chezou さん、ありがとうございます。

こんなページを公式ページとして作りたいのですが、公開のタイミングを自分たちで制御したいというニーズから、Githubページなんかでページを生成したいなぁと思ったりしています（神奈川Ruby会議01でやったやり方）。

このページを作るのをご協力いただけませんか？

**Comment by chezou** [comment]
@miyohide 了解です！まずは01のベースで作ってしまいますね。
ここのレポジトリにファイルを置く予定です。

**Comment by chezou** [comment]
@miyohide 確認ですが、github pagesを作ってプロキシしてもらう形を選ぶということで良かったでしょうか？
https://github.com/yokohamarb/minatork02/issues/8#issuecomment-102632188 だと本家へ直接PRしてるように見えたのですが、その方向は取らないという理解でいいですよね

**Comment by miyohide** [comment]
@chezou さん、Github Pagesを作ってプロキシしてもらう形を選びたいと思っています。公開のタイミングを自分たちで制御したいという思いがあり、ならばGithub Pagesの形かな？と思っています。

**Comment by chezou** [comment]
了解です。では、以前作っていただいたforkは気にしないで進めようと思います

**Comment by miyohide** [comment]
#14 のPull Requestにて対応中。

**Comment by chezou** [comment]
http://yokohamarb.github.io/minatork02 にて見れるようにしました。

残りの主なタスクは
- [ ] 参加募集の項目追加
- [ ] rko以下のドメインからproxy通す(=リリース)

です

**Comment by miyohide** [comment]
なぜか止まったままですが、Rubyの会からもリクエストされていますので、ruby-no-kai/rko-router の nginx.conf を変更してPull Requestを出す作業、誰もやらないのでしたらやります。

その前に、Pull Requestを出しているので見ていただけますか？ #15
